name: CI - Build & Test - Xcode 15

on:
    push:
      branches:
      - master
      - dev

    pull_request:
      branches:
      - master
      - dev

jobs:
  Build:
    permissions:
      pull-requests: 'write'
      # This workflow needs write access to the checks to publish
      # the results of the tests via xcresulttool.
      checks: write
        
    runs-on: macos-13
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      uses: "./.github/actions/ci_xcodebuild"
      with:
        xcode_version: "15.0.1"
        xcodebuild_destination: "platform=iOS Simulator,name=iPhone 14,OS=17.0.1"
        xcodebuild_action: "build"

  Test:
    permissions:
      # This workflow needs write access to the checks to publish
      # the results of the tests via xcresulttool.
      checks: write
    runs-on: macos-13
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      uses: "./.github/actions/ci_xcodebuild"
      with:
        xcode_version: "15.0.1"
        xcodebuild_destination: "platform=iOS Simulator,name=iPhone 14,OS=17.0.1"
        xcodebuild_action: "test"
